### ISSUE TITLE
Can you support HDR mode?

### ISSUE THREAD

**Issue by LeXwDeX** [corpnewt/ForceRGB#1]
Based on the current situation, TVs still switch back to YCbCr color in HDR mode, such as LG's C series and G series TVs.

Is it possible to support using RGB in HDR mode as well?

**Comment by corpnewt** [comment]
You may want to reach out to [Andrew Daugherity](https://gist.github.com/adaugherity) regarding that - as they're the author of the [patch-edid.rb](https://gist.github.com/adaugherity/7435890) script that ForceRGB leverages - which manages the actual edid manipulation and generating the display override.

-CorpNewt
